### ISSUE TITLE
our repo origin should start from whats live right now

### ISSUE THREAD

**Issue by enphnt** [bibzzzz/playtotm#1]
I don't have a simple way to do this off the top of my head but i'm sure its no biggie if i get a chance to think more. Its like 1:30am here... but basically we need to clone the web2py folder from pythonanywhere and use this as our base to improve from. Otherwise, its been so long we may break something and take ages to find where. Also, without including the larger web2py framework, much of the deployment related code like routes aren't under version control. Leaving them open to erosion. 

I already initiallized the pythonanywhere repo. you can clone it and start a fresh github if you want to go that route. we can then migrate what we've done here over manually. 

to clone is:  `git clone totm@ssh.pythonanywhere.com:web2py`

however, i'm open to discuss this one. we could alternatively leave that as is... i just thought myself out of it... anywho, it's under vc of some kind now at least. 

I guess a good first question to know is, where did this code come from? it was copied from pythonanywhere?

**Comment by bibzzzz** [comment]
All of the files should be up-to-date. I compiled our application in the web2py admin interface. The web2py framework should be preserved (e.g. see controllers, models, views, databases folders) - basically everything that sits under our application in web2py. If we make changes we can then package and upload, should work fine.

**Comment by bibzzzz** [comment]
Do you think a clone works better though? If so, do you want to do that and push an update?

**Comment by enphnt** [comment]
Yeh I started thinking about this last night upon discovering that building locally for web2py requires changes to the web2py routes.py. 

Ultimately, I'm just suggesting we pack all of TOTM (including any deployment config for web2py) in the repo. What u think? Can u fill the readme update and see if u get to play TOTM all the way through? If u can't, like me, we can start comparing the pythonanywhere web2py repo (which I believe we can rename too) to your Mac web2py applications package contents.

**Comment by enphnt** [comment]
i reckon we leave it... in an ideal world, web2apps are meant to be portable. So lets just leave our config in pythonanywhere for either another repo in which we ignore all applications, or something similar. Moving along to make a few refinements. Hoping to document how to setup local web2py for local playing. i'll use the wiki.
